### ISSUE TITLE
unpublished pocketsphinx patch dependencies

### ISSUE THREAD

**Issue by tkharris** [alumae/ruby-pocketsphinx-server#5]
It looks like, and I think it's mentioned in the README, that there are dependencies on unpublished pocketsphinx modifications. What are the modifications, and why are they not public? Can a patch be made available?

**Comment by alumae** [comment]
The dependencies are not yet public because I'm struggling to make them play nice with the current examples (particularly, I'm using 16 kHz sample rate while the current SVN version of pocketsphinx GST plugin is fixed to 8 kHz). I hope to work on the patch in April.

**Comment by tkharris** [comment]
Understood. Thanks alumae.

I hacked versions of pocketsphinx and ruby-pocketsphinx-server this weekend to get them to talk to each other, but it was at 8kHz. Getting it to work at 16kHz looked like it would have been easy, but, as you mentioned, not without breaking the 8kHz. It seems to be hard-coded in about 3 different places. I look forward to your 16kHz version that plays nicely with 8kHz.

I threw a couple features onto ruby-pocketsphinx-server - an ability to strip audio data out of video files, and the ability to fetch data from an url (instead of posting the data itself, a client can post an url as a parameter, and the audio is fetched by the server. Maybe when we get a common base that works I can contribute those features.

**Comment by alumae** [comment]
The patch is here:
https://sourceforge.net/tracker/?func=detail&aid=3521952&group_id=1904&atid=301904

**Comment by wiseman** [comment]
Have you tried to get the patch accepted by the pocketsphinx maintainers?  The easier access to cmn priors especially seems useful.

**Comment by alumae** [comment]
I submitted the patch to cmusphinx long time ago (http://sourceforge.net/p/cmusphinx/patches/90/), it's being ignored. I'll ask the cmusphinx developers.
