### ISSUE TITLE
Gst error on server start

### ISSUE THREAD

**Issue by jbradfield** [alumae/ruby-pocketsphinx-server#9]
Based on discussion in issue #8, I'm attempting to run the server on Ubuntu 10.04. Followed the readme, except I installed the latest release version of sphinxbase/pocketsphinx (0.8) and didn't run the patch (due to obvious version mismatch). Server attempts to launch on call, but eventually logs the following error:

E, [2014-11-18T20:01:44.385645 #25385] ERROR -- : Gst::Element expected (TypeError)
./lib/raw_recognizer.rb:57:in 'add'
./lib/raw_recognizer.rb:57:in 'create_pipeline'
./lib/raw_recognizer.rb:47:in 'initialize'
./lib/handlers/handler.rb:11:in 'new'
./lib/handlers/handler.rb:11:in 'initialize'
./lib/handlers/prettifier.rb:11:in 'initialize'
./lib/server.rb:47:in 'new'
./lib/server.rb:47
./lib/server.rb:42:in 'each'
./lib/server.rb:42
/var/lib/gems/1.8/gems/sinatra-1.4.5/lib/sinatra/base.rb:1402:in 'configure'
./lib/server.rb:17
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'gem_original_require'
/usr/lib/ruby/1.8/rubygems/custom_require.rb:31:in 'require'
config.ru:13
/var/lib/gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in 'instance_eval'
/var/lib/gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in 'initialize'
config.ru:1:in 'new'
config.ru:1

**Comment by jbradfield** [comment]
Update: this error also occurs using pocketsphinx build 11353 with the patch applied.

**Comment by alumae** [comment]
Make sure that the pocketsphinx GStreamer plugin is visible to GStreamer. 
In the same terminal as you run the ruby-pocketsphinx-server, execute:

```
 gst-inspect-0.10 pocketsphinx
```

Expected:

```
[..]
nbest-size          : Number of hypothesis in the N-best list
                    flags: readable, writable
                    Integer. Range: 1 - 1000 Default: 10 Current: 10
configured          : Set this to finalize configuration
                    flags: readable, writable
                    Boolean. Default: false Current: false
Element Signals:
  "partial-result" :  void user_function (GstElement* object,
                                      gchararray arg0,
                                      gchararray arg1,
                                      gpointer user_data);
    "result" :  void user_function (GstElement* object,
                              gchararray arg0,
                              gchararray arg1,
                              gpointer user_data);
```

**Comment by jbradfield** [comment]
Seems to be visible:

```
  [..]
  nbest-size          : Number of hypothesis in the N-best list
                        flags: readable, writable
                        Integer. Range: 1 - 1000 Default: 10 Current: 10
  decoder             : The underlying decoder
                        flags: readable
                        Boxed pointer of type "PSDecoder"
  configured          : Set this to finalize configuration
                        flags: readable, writable
                        Boolean. Default: false Current: false

Element Signals:
  "partial-result" :  void user_function (GstElement* object,
                                          gchararray arg0,
                                          gchararray arg1,
                                          gpointer user_data);
  "result" :  void user_function (GstElement* object,
                                  gchararray arg0,
                                  gchararray arg1,
                                  gpointer user_data);
```

**Comment by alumae** [comment]
Try using pocketsphinx GStreamer plugin from the command line.
Record a sentence:

```
rec tmp.wav
```

Hit Ctrl-C after a few seconds.

Then launch:

```
gst-launch-0.10 filesrc location=tmp.wav ! decodebin2 ! audioresample ! audioconvert ! pocketsphinx ! filesink location=tmp.txt
```

This should print out:

```
[....]
INFO: ngram_search_fwdtree.c(99): 788 unique initial diphones
INFO: ngram_search_fwdtree.c(147): 0 root, 0 non-root channels, 60 single-phone words
INFO: ngram_search_fwdtree.c(186): Creating search tree
INFO: ngram_search_fwdtree.c(191): before: 0 root, 0 non-root channels, 60 single-phone words
INFO: ngram_search_fwdtree.c(326): after: max nonroot chan increased to 13428
INFO: ngram_search_fwdtree.c(338): after: 457 root, 13300 non-root channels, 26 single-phone words
INFO: ngram_search_fwdtree.c(1549):       88 words recognized (7/fr)
INFO: ngram_search_fwdtree.c(1551):    20272 senones evaluated (1559/fr)
INFO: ngram_search_fwdtree.c(1553):    19995 channels searched (1538/fr), 4113 1st, 2179 last
INFO: ngram_search_fwdtree.c(1557):      259 words for which last channels evaluated (19/fr)
INFO: ngram_search_fwdtree.c(1560):     2077 candidate words for entering last phone (159/fr)
INFO: ngram_search_fwdtree.c(1562): fwdtree 0.01 CPU 0.062 xRT
INFO: ngram_search_fwdtree.c(1565): fwdtree 0.01 wall 0.058 xRT
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Got EOS from element "pipeline0".
Execution ended after 100176 ns.
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
INFO: ngram_search_fwdtree.c(430): TOTAL fwdtree 0.01 CPU 0.067 xRT
INFO: ngram_search_fwdtree.c(433): TOTAL fwdtree 0.01 wall 0.063 xRT
```

Recognition result is not printed or sent to output file, since pocketsphinx sends the results out using messages, but I just want to see if everything works as expected.

**Comment by jbradfield** [comment]
It prints out the pocketsphinx plugin config, then:

```
WARNING: erroneous pipeline: no element "decodebin2"
```

I also noticed in the inspect above that I have a "decoder" entry where your inspect doesn't. I imagine these are related.

**Comment by alumae** [comment]
Hmm, you seem to be missing the `decodebin2` GStreamer plugin which is a basic part of GStreamer 0.10. I suspect your GStreamer was not installed correctly. I don't think it has anything to do with the pocketsphinx's `decoder` property being present or not -- decodebin2 handles audio codec decoding (decoding wav or mp3 to raw samples) while the decoder of pocketsphinx handles speech recognition. And by the way, my pocketsphinx also has this property, it's just listed earlier.

**Comment by jbradfield** [comment]
Aptitude CLAIMS that `libgstreamer0.10-dev` and `libgstreamer-plugins-base0.10-dev` are installed and up-to-date (or whatever constitutes up-to-date on Ubuntu 10.04). Are there other GStreamer packages that are supposed to be installed?

**Comment by alumae** [comment]
Try `gstreamer0.10-plugins-good` or `libgstreamer0.10-plugins-good`

**Comment by jbradfield** [comment]
Installing the first one seems to have solved the problem, the server is now up and running. POSTing a file to the server currently returns `Sorry, failed to process request. Reason: No such property: cmn_mean`, which I believe was also mentioned in #8 as not being supported in current versions of pocketsphinx, so I'll see if I can comment that out without breaking the entire thing.

**Comment by alumae** [comment]
(Sorry about closing/reopening the issue, I clicked the wrong button)
Yes, you can comment out the cmn_mean related lines.

**Comment by jbradfield** [comment]
Commented out all the calls to cmn_mean related stuff and the server now works as specified. Thanks for the help!
